### ISSUE TITLE
Unlabeled data has label ?

### ISSUE THREAD

**Issue by jiarenyf** [taki0112/TripleGAN-Tensorflow#1]
https://github.com/taki0112/TripleGAN-Tensorflow/blob/40614b9c687deb38456ec7d57c87b7c2941d8a72/TripleGAN.py#L206

I wonder unlabeled input has label y ?

**Comment by taki0112** [comment]
I think so.
My code refers to the [original author's code](https://github.com/zhenxuan00/triple-gan)

There is something similar to my code in updating the classifier.
But I think I should think again.
My code is not fully implemented at present, but there are a number of things that need to be fixed.
Thank you for letting us know.

I will fix it soon.
